module.exports = {list : [
"Agiorgitiko",	"Grolleau",	"Ribolla Gialla",
"Aglianico",	"Grüner Veltliner",	"Riesling",
"Aidani",	"Kerner",	"Roditis",
"Airén",	"Koshu",	"Roussanne",
"Albariño",	"Kotsifali",	"Sagrantino",
"Aligoté",	"Lefkada",	"Sangiovese",
"Arneis",	"Malbec",	"Sangiovese & Merlot",
"Assyrtiko",	"Malmsey",	"Sauvignon Blanc & Sémillon",
"Bacchus",	"Malvasia (Malmsey)",	"Sauvignon Blanc",
"Barbera",	"Malvasia di Candia",	"Sauvignon Gris",
"Bastardo",	"Mandilaria",	"Savagnin",
"Blaufränkisch",	"Maratheftiko",	"Scheurebe/Sämling 88",
"Bobal",	"Marsanne",	"Schioppettino/Refosco",
"Bual",	"Mauzac",	"Semillon",
"Cabernet Franc",	"Mavrotragano",	"Sercial",
"Cabernet Sauvignon",	"Melon de Bourgogne",	"Seyval Blanc",
"Cabernet Sauvignon & Carmenère	Mencia",	"Shiraz & Cabernet Sauvignon",
"Cabernet Sauvignon & Franc & Merlot",	"Merlot",	"Silvaner/Sylvaner",
"Cabernet Sauvignon Blend",	"Merlot/Cabernet Franc",	"Southern Rhône Blend",
"Canaiolo",	"Merseguera",	"Syrah & Bonarda",
"Carignan",	"Montepulciano",	"Syrah & Merlot",
"Carmenère",	"Montepulciano d'Abruzzo",	"Syrah/Shiraz",
"Carricante",	"Moscatel",	"Tannat",
"Catarratto",	"Mourvèdre",	"Tempranillo/Tinto Fino",
"Catarratto Carricante blend",	"Muscadelle",	"Teroldego",
"Cava Blend",	"Muscadelle & Semillon & Sauvignon Blanc",	"Terrantez",
"Champagne Blend",	"Muscat",	"Thrapsathiri",
"Chardonnay",	"Nebbiolo",	"Timorasso",
"Chasselas",	"Negrette",	"Tinta Negra Mole",
"Chenin Blanc",	"Negroamaro",	"Tinto Fino & Caberet Sauvignon",
"Cinsault",	"Nerello",	"Torrontés",
"Coda di Volpe Bianco",	"Nero d'Avola",	"Touriga Nacional",
"Cortese",	"Northern Rhône blend",	"Trebbiano d'Abruzzo",
"Corvina, Corvinone blend",	"Uva di Troia",
"Dafni White",	"Palomino Fino",	"Verdejo",
"Dolcetto",	"Pedro Ximénez",	"Verdelho",
"Favorita/Vermentino",	"Pelaverga",	"Verdicchio",
"Feteasca Neagra",	"Perricone",	"Vermentino/Pigato",
"Feteasca Regala",	"Petit Manseng",	"Vernaccia",
"Fiano",	"Petit Verdot",	"Vernatsch/ Schiava / Trollinger",
"Frappato",	"Petite Sirah / Durif",	"Vidal Blanc",
"Freisa",	"Picolit",	"Vidiano",
"Friulano",	"Picpoul",	"Vilana White",
"Furmint",	"Pineau d'Aunis	Viognier",
"Gaglioppo",	"Pinot Meunier",	"Vitovska",
"Gamay",	"Pinot Blanc",	"Viura",
"Garganega",	"Pinot Gris/Pinot Grigio",	"Welschriesling",
"Gewürztraminer",	"Pinot Noir",	"White Rhône Blend",
"Godello",	"Pinotage",	"Xarello",
"Graciano",	"Plavac Mali",	"Xinomavro",
"Grechetto",	"Plyto",	"Zibbibo",
"Greco",	"Port Blend",	"Zinfandel",
"Grenache/Garnacha",	"Primitivo",	"Zweigelt",
"Grignolino",	"Prosecco",	 
"Grillo",	"Prugnolo Gentile/Sangiovese",
]};
